name: tecgpt
channels:
  - pytorch
  - nvidia # For CUDA if needed
  - conda-forge
  - defaults
dependencies:
  - python=3.10 # Or your preferred version
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # Example, adjust to your CUDA version
  - transformers
  - numpy
  - pandas
  - scipy
  - h5py
  - scikit-learn
  - hydra-core
  - wandb
  - optuna
  - hydra-optuna-sweeper
  - pip:
    - -r requirements.txt 