import pickle
import numpy as np
import os
import logging
from typing import Dict, Any

# logger = logging.getLogger(__name__)
# Use a more specific logger name if desired, e.g.:
logger = logging.getLogger("tecGPT.utils.scaler")

class StandardScaler:
    """
    Loads scaling parameters (mean and std for TEC and SW)
    from a .pkl file generated by preprocess_hdf5.py and provides
    an inverse_transform method for model outputs (TEC predictions).
    """
    def __init__(self, scaler_path: str, fill_value_tec: Optional[float] = -1.0):
        """
        Args:
            scaler_path (str): Path to the scaler.pkl file.
            fill_value_tec (Optional[float]): The fill value used for TEC data during scaling.
                                            This value will be preserved during inverse transform.
        """
        if not os.path.exists(scaler_path):
            logger.error(f"Scaler file not found: {scaler_path}")
            raise FileNotFoundError(f"Scaler file not found: {scaler_path}")
        
        logger.info(f"Loading scaler parameters from: {scaler_path}")
        try:
            with open(scaler_path, 'rb') as f:
                scalers = pickle.load(f)
        except Exception as e:
            logger.error(f"Error loading scaler file {scaler_path}: {e}")
            raise

        if 'tec_scaler' not in scalers or 'sw_scaler' not in scalers:
            logger.error("'tec_scaler' or 'sw_scaler' not found in the loaded scaler file.")
            raise ValueError("Scaler file must contain 'tec_scaler' and 'sw_scaler' keys.")

        self.tec_node_scaler = scalers['tec_scaler'] # This is an instance of NodeScaler
        self.sw_feature_scaler = scalers['sw_scaler'] # This is an instance of FeatureScaler
        
        # Verify that the loaded tec_scaler has the expected attributes (mean_, std_)
        if not hasattr(self.tec_node_scaler, 'mean_') or not hasattr(self.tec_node_scaler, 'std_'):
            logger.error("Loaded tec_scaler does not have 'mean_' or 'std_' attributes.")
            raise ValueError("Invalid tec_scaler object loaded.")
            
        # The fill_value for TEC should ideally be consistent with what was used during its scaling
        # The NodeScaler class in preprocess_hdf5.py already handles this fill_value correctly.
        self.fill_value_tec = self.tec_node_scaler.fill_value 
        # We can also allow overriding it, but it should match the pre-processing fill_value.
        # if passed fill_value_tec is different from tec_node_scaler.fill_value, log a warning.
        if fill_value_tec is not None and self.tec_node_scaler.fill_value != fill_value_tec:
            logger.warning(f"Provided fill_value_tec ({fill_value_tec}) is different from fill_value in loaded tec_scaler ({self.tec_node_scaler.fill_value}). Using scaler's fill_value.")


        self.n_nodes = self.tec_node_scaler.n_nodes
        logger.info(f"Scaler initialized. TEC n_nodes: {self.n_nodes}. SW n_features: {self.sw_feature_scaler.n_features}")


    def inverse_transform_tec(self, tec_data_scaled: np.ndarray) -> np.ndarray:
        """
        Inverse transforms scaled TEC data back to its original scale.
        This uses the `tec_node_scaler` (NodeScaler instance) loaded from the pickle file.

        Args:
            tec_data_scaled (np.ndarray): Scaled TEC data, typically model output.
                                         Expected shape: [B, S, N_nodes] or [B, N_nodes, S].
                                         The scaler expects the N_nodes dimension to be the last one
                                         for its internal inverse_transform method if called directly.
                                         This wrapper will handle common model output shapes.

        Returns:
            np.ndarray: TEC data in original scale, same shape as input.
        """
        if tec_data_scaled.size == 0:
            return tec_data_scaled # Return empty if input is empty

        # The NodeScaler.inverse_transform expects data of shape [..., N_nodes]
        # Model output is typically [B, N_nodes, S] or [B, S, N_nodes]
        # Our ST_LLM prediction head outputs [B, N_nodes, S]
        
        original_shape = tec_data_scaled.shape
        # logger.debug(f"inverse_transform_tec: input shape {original_shape}, n_nodes {self.n_nodes}")

        if original_shape[-1] == self.n_nodes:
            # Shape is [..., S, N_nodes] or [..., N_nodes]
            # NodeScaler.inverse_transform can handle this directly.
            # Example: [B, S, N_nodes]
            # logger.debug("Assuming last dimension is N_nodes.")
            tec_inverted = self.tec_node_scaler.inverse_transform(tec_data_scaled)
        elif original_shape[-2] == self.n_nodes and len(original_shape) > 1:
            # Shape is [..., N_nodes, S] or [B, N_nodes, S]
            # Need to permute, inverse_transform, then permute back.
            # logger.debug("Assuming second to last dimension is N_nodes. Permuting for scaler.")
            
            # Determine permutation: move N_nodes to last, S to second last
            # e.g., for [B, N_nodes, S] -> [B, S, N_nodes]
            dims = list(range(len(original_shape)))
            if len(dims) < 2:
                 raise ValueError(f"Unsupported shape for permutation: {original_shape}")
            
            # Swap the last two dimensions if N_nodes is second to last
            # For [B, N_nodes, S], original_shape[-2] is N_nodes. We need [B, S, N_nodes]
            # This means we swap axes at index -2 and -1.
            axes_permutation = dims[:-2] + [dims[-1], dims[-2]] 
            # logger.debug(f"Permuting from {dims} to {axes_permutation}")

            tec_permuted = np.transpose(tec_data_scaled, axes=axes_permutation)
            # logger.debug(f"Permuted shape for scaler: {tec_permuted.shape}")
            
            tec_inverted_permuted = self.tec_node_scaler.inverse_transform(tec_permuted)
            
            # Permute back to original dimension order [B, N_nodes, S]
            # The inverse permutation is the same if we just swapped two axes.
            # logger.debug(f"Permuting back from {axes_permutation} to {dims}")
            tec_inverted = np.transpose(tec_inverted_permuted, axes=axes_permutation)
            # logger.debug(f"Final inverted shape: {tec_inverted.shape}")

        else:
            msg = (
                f"Cannot determine N_nodes dimension for inverse_transform_tec. "
                f"Input shape: {original_shape}, N_nodes: {self.n_nodes}. "
                f"Expected N_nodes ({self.n_nodes}) to be the last or second-to-last dimension."
            )
            logger.error(msg)
            raise ValueError(msg)
        
        # Ensure fill value is preserved if it was present in the scaled data
        # The NodeScaler's inverse_transform should already handle this.
        # Example: if self.fill_value_tec is not None:
        #    mask = (tec_data_scaled == self.fill_value_tec) # Assuming fill value is same in scaled
        #    tec_inverted[mask] = self.fill_value_tec

        return tec_inverted.astype(tec_data_scaled.dtype) # Preserve dtype

    # Optional: if you also need to inverse transform SW features (e.g., for analysis)
    def inverse_transform_sw(self, sw_data_scaled: np.ndarray) -> np.ndarray:
        """
        Inverse transforms scaled Space Weather data back to its original scale.
        Args:
            sw_data_scaled (np.ndarray): Scaled SW data. 
                                         Expected shape [..., N_sw_features].
        Returns:
            np.ndarray: SW data in original scale.
        """
        if not hasattr(self, 'sw_feature_scaler') or self.sw_feature_scaler is None:
            raise AttributeError("SW Feature Scaler (sw_feature_scaler) is not initialized.")
        return self.sw_feature_scaler.inverse_transform(sw_data_scaled)
    
    # Optional: transform methods if needed for some reason (e.g. scaling new raw input)
    def transform_tec(self, tec_data_raw: np.ndarray) -> np.ndarray:
        """
        Transforms raw TEC data to scaled version.
        Args:
            tec_data_raw (np.ndarray): Raw TEC data, shape [..., N_nodes]
        Returns:
            np.ndarray: Scaled TEC data.
        """
        # Similar dimension handling as inverse_transform_tec might be needed if input shapes vary
        return self.tec_node_scaler.transform(tec_data_raw)

    def transform_sw(self, sw_data_raw: np.ndarray) -> np.ndarray:
        """
        Transforms raw SW data to scaled version.
        Args:
            sw_data_raw (np.ndarray): Raw SW data, shape [..., N_sw_features]
        Returns:
            np.ndarray: Scaled SW data.
        """
        return self.sw_feature_scaler.transform(sw_data_raw)

# Example Usage (for testing this script directly):
if __name__ == '__main__':
    # This example assumes preprocess_hdf5.py has been run and produced a scaler.pkl
    # and some dummy .npz files (or you create them here).

    # 0. Setup dummy scalers (mimicking what's in scaler.pkl)
    dummy_scaler_path = "../../processed_data_dummy_scaler/scaler.pkl" # Adjust path
    dummy_data_dir = "../../processed_data_dummy_scaler/"
    os.makedirs(os.path.dirname(dummy_scaler_path), exist_ok=True)

    N_NODES_DUMMY = 10
    N_SW_FEAT_DUMMY = 5
    FILL_VAL_DUMMY = -1.0

    # Create a dummy NodeScaler instance
    class DummyNodeScaler:
        def __init__(self, n_nodes, fill_value):
            self.n_nodes = n_nodes
            self.fill_value = fill_value
            # Use simpler mean/std for testing inverse transform logic
            self.mean_ = np.random.rand(n_nodes) * 10 
            self.std_ = np.random.rand(n_nodes) * 2 + 0.5 # Avoid std near zero
            if fill_value is not None:
                 # For testing, assume some nodes might be entirely fill_value
                 self.mean_[0] = 0 # Scaler would handle this
                 self.std_[0] = 1

        def transform(self, data):
            original_shape = data.shape
            data_reshaped = data.reshape(-1, self.n_nodes)
            transformed = np.zeros_like(data_reshaped)
            for i in range(self.n_nodes):
                col = data_reshaped[:, i]
                if self.fill_value is not None:
                    mask = (col == self.fill_value)
                    transformed[~mask, i] = (col[~mask] - self.mean_[i]) / self.std_[i]
                    transformed[mask, i] = self.fill_value
                else:
                    transformed[:, i] = (col - self.mean_[i]) / self.std_[i]
            return transformed.reshape(original_shape)

        def inverse_transform(self, data):
            original_shape = data.shape
            data_reshaped = data.reshape(-1, self.n_nodes)
            inverted = np.zeros_like(data_reshaped)
            for i in range(self.n_nodes):
                col = data_reshaped[:, i]
                if self.fill_value is not None:
                    mask = (col == self.fill_value)
                    inverted[~mask, i] = (col[~mask] * self.std_[i]) + self.mean_[i]
                    inverted[mask, i] = self.fill_value
                else:
                    inverted[:, i] = (col * self.std_[i]) + self.mean_[i]
            return inverted.reshape(original_shape)

    # Create a dummy FeatureScaler instance (mimicking Sklearn StandardScaler)
    class DummyFeatureScaler:
        def __init__(self, n_features):
            self.n_features = n_features
            self.scaler_ = None # Not actually fitting, just providing structure
            self.mean_ = np.random.rand(n_features) * 5
            self.scale_ = np.random.rand(n_features) + 0.5

        def transform(self, data):
            return (data - self.mean_) / self.scale_
        
        def inverse_transform(self, data):
            return (data * self.scale_) + self.mean_

    dummy_tec_scaler = DummyNodeScaler(N_NODES_DUMMY, FILL_VAL_DUMMY)
    dummy_sw_scaler = DummyFeatureScaler(N_SW_FEAT_DUMMY)

    with open(dummy_scaler_path, 'wb') as f:
        pickle.dump({'tec_scaler': dummy_tec_scaler, 'sw_scaler': dummy_sw_scaler}, f)
    logger.info(f"Created dummy scaler.pkl at {dummy_scaler_path}")

    # 1. Instantiate the StandardScaler
    try:
        scaler = StandardScaler(scaler_path=dummy_scaler_path, fill_value_tec=FILL_VAL_DUMMY)
        logger.info("StandardScaler instantiated successfully.")
    except Exception as e:
        logger.error(f"Failed to instantiate StandardScaler: {e}")
        exit()

    # 2. Create some dummy scaled TEC data (as if from a model)
    B, S = 2, 3 # Batch size, Sequence length for prediction
    # Case 1: Model output [B, N_nodes, S] - this is what ST_LLM output head produces
    dummy_scaled_tec_model_output1 = np.random.randn(B, N_NODES_DUMMY, S).astype(np.float32)
    # Introduce some fill values for testing preservation
    if FILL_VAL_DUMMY is not None:
        dummy_scaled_tec_model_output1[0, 0, 0] = FILL_VAL_DUMMY # A single fill value
        dummy_scaled_tec_model_output1[0, 1, :] = FILL_VAL_DUMMY # A whole node-sequence

    # Case 2: Model output [B, S, N_nodes]
    dummy_scaled_tec_model_output2 = np.random.randn(B, S, N_NODES_DUMMY).astype(np.float32)
    if FILL_VAL_DUMMY is not None:
        dummy_scaled_tec_model_output2[0, 0, 0] = FILL_VAL_DUMMY
        dummy_scaled_tec_model_output2[0, 1, 1] = FILL_VAL_DUMMY
    
    # 3. Test inverse_transform_tec
    logger.info("\nTesting inverse_transform_tec...")
    try:
        logger.info(f"Input shape (Case 1: [B, N_nodes, S]): {dummy_scaled_tec_model_output1.shape}")
        tec_original_scale1 = scaler.inverse_transform_tec(dummy_scaled_tec_model_output1)
        logger.info(f"Output shape (Case 1): {tec_original_scale1.shape}")
        assert tec_original_scale1.shape == dummy_scaled_tec_model_output1.shape
        if FILL_VAL_DUMMY is not None:
            assert tec_original_scale1[0,0,0] == FILL_VAL_DUMMY, "Fill value not preserved in Case 1, single element"
            assert np.all(tec_original_scale1[0,1,:] == FILL_VAL_DUMMY), "Fill value not preserved in Case 1, node-sequence"
        logger.info("Case 1 inverse transform successful and fill values preserved.")

        # Test a small part of the math for non-fill value
        # Raw = Scaled * std + mean
        # For Case 1, node 2 (index 2), first sample, first step
        # This test is against the DUMMY scaler values.
        idx_b, idx_node, idx_s = 0, 2, 0
        if dummy_scaled_tec_model_output1[idx_b, idx_node, idx_s] != FILL_VAL_DUMMY:
            expected_val = (dummy_scaled_tec_model_output1[idx_b, idx_node, idx_s] * scaler.tec_node_scaler.std_[idx_node]) + scaler.tec_node_scaler.mean_[idx_node]
            actual_val = tec_original_scale1[idx_b, idx_node, idx_s]
            assert np.isclose(expected_val, actual_val), f"Inverse transform math check failed for Case 1. Expected {expected_val}, got {actual_val}"
            logger.info("Case 1 non-fill value inverse transform math check passed.")


        logger.info(f"\nInput shape (Case 2: [B, S, N_nodes]): {dummy_scaled_tec_model_output2.shape}")
        tec_original_scale2 = scaler.inverse_transform_tec(dummy_scaled_tec_model_output2)
        logger.info(f"Output shape (Case 2): {tec_original_scale2.shape}")
        assert tec_original_scale2.shape == dummy_scaled_tec_model_output2.shape
        if FILL_VAL_DUMMY is not None:
            assert tec_original_scale2[0,0,0] == FILL_VAL_DUMMY, "Fill value not preserved in Case 2"
        logger.info("Case 2 inverse transform successful and fill value preserved.")

    except Exception as e:
        logger.error(f"Error during inverse_transform_tec test: {e}", exc_info=True)

    # 4. (Optional) Test inverse_transform_sw if implemented and needed
    # dummy_scaled_sw = np.random.randn(B, P_history_dummy, N_SW_FEAT_DUMMY) # Example shape
    # sw_original_scale = scaler.inverse_transform_sw(dummy_scaled_sw)
    # logger.info(f"SW original scale shape: {sw_original_scale.shape}")
    
    # Clean up dummy scaler
    # os.remove(dummy_scaler_path)
    # os.rmdir(os.path.dirname(dummy_scaler_path))
    # logger.info(f"Cleaned up dummy scaler: {dummy_scaler_path}")
    logger.info("\nStandardScaler direct test finished.") 