# conf/trainer/default.yaml
batch_size: 32
learning_rate: 0.0001 # 初始学习率
epochs: 50
patience: 10 # 早停的耐心轮数
weight_decay: 0.01
clip_grad_norm: 1.0
print_every_epochs: 1
optimizer_type: "AdamW" # "AdamW" 或 "Ranger"
use_amp: true # 是否使用混合精度训练 